# Generated by Django 3.2.15 on 2022-09-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departaments', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отдел')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestatproject.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответ на вопрос')),
                ('ball', models.IntegerField(blank=True, null=True, verbose_name='Бал')),
                ('id_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestatproject.question')),
            ],
        ),
    ]
