# Generated by Django 3.2.15 on 2022-09-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attestatproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отдел')),
                ('users', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Пользователь')),
                ('questions', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вопрос')),
                ('category', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Категория')),
                ('select_answers', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Выбранный ответ')),
                ('good_answers', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Правильный ответ')),
                ('result_balls', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Балл')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='id_questions',
        ),
        migrations.RemoveField(
            model_name='departament',
            name='author',
        ),
        migrations.RemoveField(
            model_name='departament',
            name='id_questions',
        ),
        migrations.AddField(
            model_name='answer',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attestatproject.question'),
        ),
        migrations.AddField(
            model_name='departament',
            name='ID_User_Dep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id_Пользователя_отдела'),
        ),
        migrations.AddField(
            model_name='departament',
            name='numberDep',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер отдела'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Дело-производство', 'Дело-производство'), ('Обычный', 'Обычный'), ('По кадровому законодательству', 'По кадровому законодательству'), ('По трудовому законодательству', 'По трудовому законодательству')], max_length=1000, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='question',
            name='id_departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attestatproject.departament'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ball',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], max_length=10, null=True, verbose_name='Бал'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='departaments',
            field=models.CharField(blank=True, choices=[('Волгоградский производственный участок', 'Волгоградский производственный участок'), ('Отдел государственной кадастровой оценки земельного фонда', 'Отдел государственной кадастровой оценки земельного фонда'), ('Отдел государственной кадастровой оценки объектов капитального строительства', 'Отдел государственной кадастровой оценки объектов капитального строительства'), ('Отдел информационных технологий', 'Отдел информационных технологий'), ('Отдел кадровой работы и делопроизводства', 'Отдел кадровой работы и делопроизводства'), ('Отдел материально-технического обеспечения и государственных закупок', 'Отдел материально-технического обеспечения и государственных закупок'), ('Отдел пространственных данных и информаицонного взаимодействия', 'Отдел пространственных данных и информаицонного взаимодействия'), ('Отдел хранения и выдачи информации', 'Отдел хранения и выдачи информации'), ('Районные отделы', 'Районные отделы'), ('Секретарь', 'Секретарь'), ('Финансово-экономический отдел', 'Финансово-экономический отдел'), ('Юридический отдел', 'Юридический отдел')], max_length=1000, null=True, verbose_name='Отдел'),
        ),
    ]
