# Generated by Django 3.2.15 on 2022-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestatproject', '0002_auto_20220921_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('по делопроизводству', 'по делопроизводству'), ('Обычный', 'Обычный'), ('по охране труда', 'по охране труда'), ('по трудовому законодательству', 'по трудовому законодательству')], max_length=1000, null=True, verbose_name='Категория'),
        ),
    ]
