# Generated by Django 3.2.13 on 2022-10-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestatproject', '0006_alter_departament_departaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отдел')),
                ('users', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Пользователь')),
                ('result_balls', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общий Балл')),
                ('res', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Результат Тестирования')),
                ('dt', models.DateField(blank=True, max_length=1000, null=True, verbose_name='Дата прохождения')),
            ],
        ),
    ]
